import { test, expect } from "@playwright/test";
test("mode switching preserves editor drafts, selection attaches, and stale files never silently overwrite",async({page},info)=>{
  await page.goto("/tests/ui/fixture.html?scenario=code");
  await page.getByRole("combobox",{name:"工作模式"}).selectOption("code");
  await page.locator(".code-tree-row").getByRole("button",{name:"▸ ▣ src",exact:true}).click();
  await page.locator(".code-tree-row").getByRole("button",{name:"· main.ts",exact:true}).click();
  const editor=page.locator(".code-editor-area .cm-content").last();
  await expect(editor).toContainText("Hello Simple");
  await editor.click();await page.keyboard.press("Control+End");await page.keyboard.type("// manual edit");
  await page.getByRole("combobox",{name:"工作模式"}).selectOption("simple");
  await expect(page.locator(".code-workspace")).toBeHidden();
  await page.getByRole("combobox",{name:"工作模式"}).selectOption("code");
  await expect(editor).toContainText("manual edit");
  await editor.click();await page.keyboard.press("Control+a");
  await page.getByRole("button",{name:"选区加入对话",exact:true}).click();
  await expect(page.locator(".composer")).toContainText("粘贴");
  await page.evaluate(async()=>{const modulePath="/node_modules/@tauri-apps/api/core.js";const api=await import(modulePath);await api.invoke("test_external");window.dispatchEvent(new Event("focus"));});
  await expect(page.getByText("文件已在外部修改。你的编辑仍保留，请比较后合并。",{exact:false})).toBeVisible();
  await expect(editor).toContainText("manual edit");
  await expect(page.getByRole("button",{name:"保存",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"比较",exact:true}).click();
  await expect(page.locator(".code-compare-half").first()).toContainText("AI changed");
  await page.screenshot({path:info.outputPath("simple-code-conflict.png")});
  await page.getByRole("button",{name:"保留编辑，以磁盘版本为保存基准"}).click();
  await page.getByRole("button",{name:"保存",exact:true}).click();
  await expect(page.locator(".code-status")).toContainText("已保存");
  await page.getByRole("button",{name:"返回编辑",exact:true}).click();
  await page.screenshot({path:info.outputPath("simple-code.png")});
  await page.reload();
  await expect(page.getByRole("combobox",{name:"工作模式"})).toHaveValue("code");
});
